/* Vocabulary data embedded from specification */
const RAFITSARY = [
  {mg:"antsasa-demaka",fr:"demi-plan",en:""},
  {mg:"antsasa-kitsy",fr:"demi-droite",en:""},
  {mg:"antsasaky ny manodidina",fr:"demi-périmètre",en:""},
  {mg:"ara-joro",fr:"angulaire",en:""},
  {mg:"ara-kadiry",fr:"volumique",en:""},
  {mg:"bika ara-drafitsary",fr:"forme géométrique",en:""},
  {mg:"biloka",fr:"courbe",en:""},
  {mg:"biloka fanehoana",fr:"courbe représentative",en:""},
  {mg:"biloka manongoa",fr:"courbe cumulative",en:""},
  {mg:"biloka mifotitra",fr:"courbe inverse",en:""},
  {mg:"dimilafy",fr:"pentagone",en:""},
  {mg:"efa-joro",fr:"carré / quadrangulaire / rectangulaire",en:"square"},
  {mg:"efadafy",fr:"quadrilatère",en:""},
  {mg:"efajoron-demaka",fr:"tétraèdre",en:""},
  {mg:"efamira",fr:"carré",en:""},
  {mg:"elipsa",fr:"ellipse",en:"ellipse"},
  {mg:"elipsoîda",fr:"ellipsoïde",en:""},
  {mg:"enimira / enindafy / eninjoro",fr:"hexagone",en:""},
  {mg:"eoklidiana",fr:"euclidien",en:""},
  {mg:"fampiharana refin-joro",fr:"trigonométrie",en:""},
  {mg:"fananganana ara-drafitsary",fr:"construction géométrique",en:""},
  {mg:"faribolana",fr:"cercle",en:"circle"},
  {mg:"fifanahafana",fr:"similitude",en:""},
  {mg:"fifanahafana mandrorona",fr:"similitude indirecte",en:""},
  {mg:"fifanahafana mivantana",fr:"similitude directe",en:""},
  {mg:"fikisahana / kisaka",fr:"translation",en:""},
  {mg:"fimiran-jotra / firaizotra",fr:"parallélisme",en:""},
  {mg:"fimirarefy / fimirazeva",fr:"isométrie",en:""},
  {mg:"firaika",fr:"inclinaison / pente",en:""},
  {mg:"firaikan'ny hitsy iray",fr:"pente d'une droite",en:""},
  {mg:"fitsimbadihana",fr:"transposition",en:""},
  {mg:"goba",fr:"cube",en:""},
  {mg:"hakitsoloha",fr:"conicité",en:""},
  {mg:"halalaka",fr:"largeur",en:"width"},
  {mg:"hiperbôla",fr:"hyperbole",en:""},
  {mg:"hitsy",fr:"droite",en:""},
  {mg:"hitsy iraizotra / hitsy mirazotra",fr:"droites parallèles",en:""},
  {mg:"hitsy mifampijadona",fr:"droites perpendiculaires",en:""},
  {mg:"hitsy mifanapaka",fr:"droites concourantes / sécantes",en:""},
  {mg:"iaraiivo / miraîvo",fr:"concentrique",en:""},
  {mg:"iraizopototra mahitsizoro",fr:"trapèze rectangle",en:""},
  {mg:"iraizotongotra",fr:"prisme",en:""},
  {mg:"iraizotongotra mahitsy",fr:"prisme droit",en:""},
  {mg:"iraizotra",fr:"parallèle / colinéaires",en:""},
  {mg:"ivom-ponja",fr:"barycentre",en:""},
  {mg:"ivomparibolana",fr:"centre d'un cercle",en:"center of a circle"},
  {mg:"ivon-kaavo / mahitiivo",fr:"orthocentre",en:""},
  {mg:"jadona",fr:"perpendiculaire",en:""},
  {mg:"jadonivo",fr:"médiatrice",en:""},
  {mg:"jeometria / rafitsary",fr:"géométrie",en:"geometry"},
  {mg:"kantsam-paribolana",fr:"arc de cercle",en:""},
  {mg:"kantsana",fr:"segment",en:""},
  {mg:"karteziana",fr:"cartésien",en:""},
  {mg:"kasika",fr:"tangente",en:"tangent"},
  {mg:"kasitsiefaina",fr:"asymptote",en:""},
  {mg:"kibola",fr:"sphérique",en:""},
  {mg:"kosina",fr:"cosinus",en:""},
  {mg:"kôkasika",fr:"cotangente",en:""},
  {mg:"kônika / tsikatra",fr:"conique",en:""},
  {mg:"lejo",fr:"hypoténuse",en:"hypotenuse"},
  {mg:"lemaka",fr:"plan",en:"plane"},
  {mg:"lemaka marindrano",fr:"plan horizontal",en:""},
  {mg:"lemaka mijidina",fr:"plan vertical",en:""},
  {mg:"maridrefy",fr:"échelle",en:"scale"},
  {mg:"marolafimira / maromira",fr:"polygone régulier",en:""},
  {mg:"marolafy / maromira",fr:"polygone",en:""},
  {mg:"marozorondemaka",fr:"polyèdre",en:""},
  {mg:"mifampijadona",fr:"orthogonal / perpendiculaire",en:"orthogonal"},
  {mg:"miraefadafy",fr:"losange",en:""},
  {mg:"miralemaka",fr:"coplanaire",en:""},
  {mg:"mirarefy",fr:"isométrique",en:""},
  {mg:"mirazotra",fr:"parallèles",en:""},
  {mg:"mpanivo",fr:"médiane",en:""},
  {mg:"radiana",fr:"radian",en:""},
  {mg:"refim-paribolana",fr:"circonférence",en:""},
  {mg:"rirakitso",fr:"pyramide",en:""},
  {mg:"roatava",fr:"dièdre",en:""},
  {mg:"roazodafy",fr:"parallélogramme",en:""},
  {mg:"salavalava",fr:"ellipse",en:"ellipse"},
  {mg:"sary ara-drafitsary",fr:"dessin géométrique",en:""},
  {mg:"savaivo",fr:"diamètre",en:"diameter"},
  {mg:"savazoro",fr:"diagonale",en:""},
  {mg:"sina",fr:"sinus",en:""},
  {mg:"sondry",fr:"cône",en:""},
  {mg:"tarehy ara-drafitsary",fr:"figure géométrique",en:""},
  {mg:"teboka",fr:"point",en:"point"},
  {mg:"telolafy",fr:"triangle",en:"triangle"},
  {mg:"telolafy miralafy / telolafy telomira",fr:"triangle équilatéral",en:""},
  {mg:"telolafy miraranjo",fr:"triangle isocèle",en:""},
  {mg:"telozodrirana",fr:"parallélépipède",en:""},
  {mg:"tsipika mahitsy",fr:"ligne droite",en:""},
  {mg:"valotava / efajoron-demaka",fr:"tétraèdre",en:""},
  {mg:"varingarina",fr:"cylindre",en:""},
  {mg:"vohidroa",fr:"ovale",en:""},
  {mg:"volan-tsinana",fr:"demi-cercle",en:"half-circle"},
  {mg:"zoro dombo",fr:"angle obtus",en:""},
  {mg:"zoro filo",fr:"angle aigu",en:""},
  {mg:"zoro fisaka",fr:"angle plat",en:""},
  {mg:"zoro mahitsy",fr:"angle droit",en:""}
];
const RAFITRISA = [{mg:"adisanina",fr:"addition",en:"addition"},{mg:"fanalana",fr:"soustraction",en:"subtraction"},{mg:"songatombo",fr:"multiple",en:""},{mg:"mizara",fr:"division",en:"division"},{mg:"isa tsimivaky",fr:"nombre entier",en:""},{mg:"isa voasaina",fr:"nombre rationnel",en:""},{mg:"isa tsy azo tsinjaraina",fr:"nombre premier",en:""},{mg:"isa haro",fr:"nombre complexe",en:""},{mg:"isa tafolo",fr:"nombre décimal",en:""},{mg:"tsiankasa",fr:"impair",en:"odd"},{mg:"ankasa",fr:"pair",en:"even"},{mg:"tsiefa",fr:"infini",en:"innumerable"},{mg:"ampaha",fr:"fraction",en:""},{mg:"ampaharoa",fr:"demi / moitié",en:"half"},{mg:"ampahatelo",fr:"tiers",en:"third"},{mg:"ampahefatra",fr:"quart / quartier",en:"fourth"},{mg:"ampahazato / isan-jato",fr:"centième / pourcentage",en:"percent"},{mg:"vokatra ny fanampiana",fr:"somme",en:"sum"},{mg:"vokatry ny fizaràna",fr:"quotient",en:""},{mg:"fimirana",fr:"égalité",en:""},{mg:"tsifimirana",fr:"inégalité",en:""},{mg:"famantarana miabo",fr:"signe plus",en:"plus sign"},{mg:"famantarana miiba",fr:"signe moins",en:"minus sign"}];
const ALIJEBRA = [{mg:"lefa",fr:"fonction",en:"function"},{mg:"fampimirana",fr:"équation",en:""},{mg:"fampimirana ambaratonga voalohany",fr:"équation du premier degré",en:""},{mg:"fampimirana ambaratonga faharoa",fr:"équation du second degré",en:""},{mg:"vala",fr:"ensemble",en:""},{mg:"vondrona foana",fr:"ensemble vide",en:""},{mg:"vondrona fiandohana",fr:"ensemble de départ",en:""},{mg:"vondrona fiantefana",fr:"ensemble d'arrivée",en:""},{mg:"vaha",fr:"solution",en:""},{mg:"tsilo",fr:"vecteur",en:""},{mg:"vokatra kalera",fr:"produit scalaire",en:""},{mg:"vokatra tsilo",fr:"produit vectoriel",en:""},{mg:"maromiantoana",fr:"polynôme",en:""},{mg:"roamiantoana",fr:"binôme",en:""},{mg:"telomiantoana",fr:"trinôme",en:"trinomial"}];
const ANTONTAN_ISA = [{mg:"antontanisa / statistika",fr:"statistique",en:""},{mg:"faminavinana",fr:"estimation",en:""},{mg:"kartila",fr:"quartile",en:""},{mg:"mpitranga",fr:"événement",en:""},{mg:"mpitranga miravona",fr:"événement équiprobable",en:""},{mg:"ovaka",fr:"variance",en:""},{mg:"sala / sala aritmetika",fr:"moyenne",en:""},{mg:"vina",fr:"probabilité",en:""},{mg:"vina misy fepetra",fr:"probabilité conditionnelle",en:""},{mg:"voalanja",fr:"pondéré",en:"weighted"}];
const GENERAL = [{mg:"asamarika mamadika",fr:"opération commutative",en:""},{mg:"asamarika tokana",fr:"opération",en:""},{mg:"doko miavaka",fr:"identité",en:""},{mg:"fanadihadiana mifangaro isa",fr:"analyse combinatoire",en:""},{mg:"fandraisana an-tsapaka",fr:"tirage au hasard",en:""},{mg:"fanjohian-kevitra ara-pihoarana",fr:"raisonnement par récurrence",en:""},{mg:"fifandraisana mandahatra",fr:"relation d'ordre",en:""},{mg:"fifanesena",fr:"suite",en:""}];
